import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/store/provider";
import { QueryProvider } from "@/lib/queryProvider";
import AuthCheckWrapper from "./components/common/AuthCheckWrapper";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <QueryProvider>
          <Providers>
            <Toaster />
            <AuthCheckWrapper>{children}</AuthCheckWrapper>
          </Providers>
        </QueryProvider>
      </body>
    </html>
  );
}
